---
- hosts: appservers
  become: yes
  gather_facts: yes
  tasks:
  - name: Install Java Runtime Environment
    shell:
      cmd: yum install fontconfig java-11-openjdk -y
  - name: Download latest Jenkins
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Run the key for Jenkins
    shell:
      cmd: 'rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key'  
  - name: install Jenkins
    yum:
      name: jenkins
      state: latest

  - name: Creating a Jenkins service
    systemd:
      name: jenkins.service
      enabled: true
      state: restarted
...