- hosts: web_servers:app_servers
  become: true
  gather_facts: no
  tasks:
    - name: Switching off the swap memory for every system reboot
      shell: |
        swapoff -a 
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Installation of packages and any container run-time
      apt: 
        update-cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Adding the Docker official GPG repository keys # In 'gpg', add --yes to prevent propt y/N, if already exists.
      shell: |
        mkdir -p /etc/apt/keyrings 
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg  
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Installing Containerd
      apt: 
        update-cache: yes
        name: 
          - containerd.io

    - name: Generate default configuration file and Changing the default configuration
      shell: | 
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemCgroup \= false/SystemCgroup \= true/g' /etc/containerd/config.toml
    - name: Restart and Enable containerd
      service:
        name: containerd
        state: restarted
        enabled: yes
    - name: Add kernel settings and Enable IP tables(CNI Prerequisites)
      copy:
        content: | 
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
    - name: execute commands
      shell:
        modprobe overlay
        modprobe br_netfilter
    - name: configuration file for kubernetes
      copy:
        content: | 
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf
    - name: execute command to
      shell:
        sysctl --system

    - name: Installing packages and configuring kubeadm, kubelet and kubectl
      apt:
        update-cache: yes
        name: 
          - ca-certificates
          - apt-transport-https
          - curl

    - name: Download the Google cloud public signing key # In 'gpg', add --yes to prevent propt y/N, if already exists.
      shell:
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    - name: Add Kubernetes repository
      shell:
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: Installing the kubeadm, kubectl, kubelet
      apt: 
        update-cache: yes
        name:
          - kubeadm
          - kubectl
          - kubelet
    - name:  apt-mark hold will prevent the package from being automatically upgraded or removed 
      shell:
        apt-mark hold kubelet kubeadm kubectl
    - name: Enable and start kubelet service
      service:
        name: kubelet
        state: restarted
        enabled: yes