---
- hosts: all
  gather_facts: False
  become: true
  tasks: 
  - name: Create a file
    file: 
      path: /tmp/mithtechno2.log
      mode: 1777
      state: touch
      owner: ec2-user
      group: ec2-user
...